### PR TITLE
Update to Trails 2.0

### PR DESCRIPTION
**Pull request by scott-wyatt**

### CODE REVIEW

**Comment by jaumard** [comment]
Thanks :) but I think this repo is completely useless with Trails 2.0, we should be able to use class directly from Trails now (not tested)

**Comment by scott-wyatt** [comment]
Good point, I will try

**Comment by scott-wyatt** [comment]
Okay, I tried what you recommended, it still is an issue with trails and the way it exports classes. 
trails now has `service.js`,`controller.js`, `model.js`, `policy.js` files but they export the modules in the exact same way as they did before which is still no good. I'm thinking I might make a PR on the 2.0 RC to change this to the modular approach that es6 will expect and still works in node 4.

**Comment by jaumard** [comment]
Arf :( so I merge this no problem thanks for the PR ^^

**Comment by scott-wyatt** [comment]
Publish to NPM as well? :-)

**Comment by jaumard** [comment]
Yes done :)

**Pull request merged**
